name: CI

on:
  push:
    branches: [main, research/recon-spec-portfolio]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install 
      - name: Build site
        run: npm run build

  # Optional lighthouse check (disabled by default)
  # lighthouse:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Build site
  #       run: npm run build
  #     - name: Run Lighthouse CI
  #       run: echo "TODO: Add lighthouse-ci if desired"
